### PR TITLE
Package 3.21.5

### PR DESCRIPTION
**Pull request by selfxp**

### CODE REVIEW

**Review by tysonnorris — APPROVED** [review]
LGTM

**Comment by selfxp** [comment]
@dgrove-oss any idea why the travis build is not starting, as it's blocking the merge. I think we've seen this issue before, however is seemed to be fixed?

**Comment by dgrove-oss** [comment]
Different problem this time.  Last time it was that we were trying to use a no-longer-available nodejs-10 environment.  This time it is `Owner apache user license exceeded.`

https://app.travis-ci.com/github/apache/openwhisk-client-js/requests

My guess is that this will get cleared up by ASF asking for and being granted more licenses

**Comment by dgrove-oss** [comment]
I closed and re-opened; travis started right up.   I can't explain it.

**Comment by selfxp** [comment]
Oh that's a good trick. I guess it didn't have resources at the time of commit, and it did at the time of close/re-open which triggered a new event. I'll use this from now on, as I can't manually start the build from travis..

**Pull request merged**
