### PR TITLE
Support client retries

### PR DESCRIPTION
**Pull request by moritzraho**
This PR adds support for retries in the client using the [async-retry](https://www.npmjs.com/package/async-retry) package. Like now, the default is no retries.
Retries are performed on http errors and all 4xx and 5xx error codes. This can be re-discussed, e.g. retries on 4xx might not be wanted.
Default values might be set differently too: https://github.com/apache/openwhisk-client-js/pull/227/files#diff-ca407d959d33ce92a7f7efee354a5ea5e6e61fcd797d32c04205e429a074ed54R160

This has been tested via unit tests and manually.

Api doc and README have been updated too.

### CODE REVIEW

**Comment by moritzraho** [comment]
Thanks for your reviews @selfxp and @rabbah !
Closed the comments, in for another quick round of review ?

**Comment by moritzraho** [comment]
> @moritzraho is there a missing commit with the recent changes?

Yeah haha 😅

**Comment by dgrove-oss** [comment]
We can't change things through the GitHub UI, but can configure via .asf.yaml.  I believe it is already set correctly (https://github.com/apache/openwhisk-client-js/blob/master/.asf.yaml#L30-L38).

**Comment by purplecabbage** [comment]
Do we have an idea of when this would be released? @rabbah @dgrove-oss @selfxp

**Comment by selfxp** [comment]
I'm not on the [PMC](https://projects.apache.org/committee.html?openwhisk), @tysonnorris will help release this tomorrow morning

**Pull request merged**
