### PR TITLE
fix: Do not modify input params. This closes #230

### LINKED ISSUE #230: service requests modify query string with every retry
This was also reported here: https://github.com/adobe/aio-cli-plugin-app/issues/504
The issue is that `client.js:rp` ( request promise wrapper) builds a query string and modifies the object reference url, so on every retry it gets longer..

`/api/v1/namespaces/ns/actions/pkg/action?overwrite=true`
`/api/v1/namespaces/ns/actions/pkg/action?overwrite=true?overwrite=true`
`/api/v1/namespaces/ns/actions/pkg/action?overwrite=true?overwrite=true?overwrite=true`

```
OpenWhiskError: PUT host/api/v1/namespaces/ns/actions/pkg/action?overwrite=true?overwrite=true?overwrite=true Returned HTTP 400 (Bad Request) --> "The query parameter 'overwrite' was malformed:
'true?overwrite=true?overwrite=true' is not a valid Boolean value"
```

### PR DESCRIPTION
**Pull request by purplecabbage**
See #230

### CODE REVIEW

**Review by rabbah — APPROVED** [review]
lgtm - is there a test that can be added?

**Comment by purplecabbage** [comment]
@rabbah I added a test that passes, I also made sure the test failed in the previous version.

**Review by rabbah — APPROVED** [review]
🎉 thanks for adding a test.

**Review by selfxp — APPROVED** [review]
👍

**Pull request merged**
